services:
  library_db:
    image: postgres:latest
    container_name: library_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: manage_library
    volumes:
      - library_db_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - common-network

networks:
  common-network:
    driver: bridge

volumes:
  library_db_data: